"""adding iban column in complainer model

Revision ID: e3d2e20b5467
Revises: d1daff8b50c6
Create Date: 2023-04-18 09:04:01.433633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d2e20b5467'
down_revision = 'd1daff8b50c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complainers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iban', sa.String(length=22), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complainers', schema=None) as batch_op:
        batch_op.drop_column('iban')

    # ### end Alembic commands ###
